- file: GBR0.webp
  title: Queen Monroe II
  author: Place-holder
  text: Queen Monroe II ruled the country of Great Britain from 1946 to 1953
  type: Europe
  coordinates: [51.5072, -0.1276]

- file: NED0.webp
  title: Queen Saotome VI
  author: Place-holder
  text: Queen Saotome VI has been in war for 5 years with the United States.
        Legends has it she mounts on a Shibe.
  type: Europe
  coordinates: [52.1326, 5.2913]

- file: DEN0.webp
  title: Denmark for the lols
  author: Place-holder
  text: Denmark and Sweden are still at it again
  type: Europe
  coordinates: [56.2639, 9.5018]

- file: INT0.webp
  title: United Nations of Monroe
  author: Place-holder
  text: Olivia Monroe united the nations
  type: International

- file: INT1.webp
  title: United States of Socks
  author: Place-holder
  text: Each state is governed by a sock
  type: International

- file: INT2.webp
  title: NASA
  author: Place-holder
  text: NASA is looked after by owoClap
  type: International

- file: Commonlove.webp
  title: Common Love
  author: LeanFries
  text: Flag representing an international association of 56 countries united
        by their shared history and love for Olivia Monroe
  type: International

- file: OliRSA.webp
  title: Oligarchy of South Africa
  author: LeanFries
  text: The flag of South Africa under the rule of Olivia Monroe and her chosen
        gal pals; their policies are driven by DFE and increasing birth rates.
  type: Africa
  coordinates: [-33.9221, 18.4231]

- file: oliun1v22.webp
  title: United Olivians
  author: Relishes
  text: Centre of the world? The North Pole? Paaaah! We know where it is!
  type: International

- file: theoliviarampant.webp
  title: The Olivia Rampant
  author: Relishes
  text: Our happy girl shows off her feisty side - Rampant, with hot pink
        stiletto nails, and shreds
  type: Europe
  coordinates: [55.066667, -6.000000]

- file: navi_ioc.webp
  title: International Olivia Committee
  author: Navi
  text: Every four years, ballet is the main event at the Olimpics. Officially,
        this is held at the Olisseum, but some say the grand finals are held in
        a \"dungeon\" deep underground
  type: International

- file: ninja_flag.webp
  title: The Fertile Crescent
  author: ninjasaurusrexatron
  text: 5 kids? There\'s no way you want 8 kids. 11 kids is too many. How are we
        supposed to take care of 15 kids?
  type: Asia
  coordinates: [37.887389, 41.132222]
